# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations


def seed_services(apps, schema_editor):
    from apps.services.catalog import seed_catalog

    seed_catalog(
        service_model=apps.get_model("services", "Service"),
        problem_model=apps.get_model("services", "ServiceProblem"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_services, migrations.RunPython.noop),
    ]
