# Generated by Django 5.2.17 on 2026-08-20 03:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicRequestOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_offers', to='accounts.mechanicprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mechanic', 'status'], name='service_req_mechani_c29f03_idx'), models.Index(fields=['request', 'status'], name='service_req_request_257e27_idx')],
                'constraints': [models.UniqueConstraint(fields=('request', 'mechanic'), name='unique_offer_per_mechanic_request')],
            },
        ),
    ]
