# Generated by Django 5.2.17 on 2026-09-13 00:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('service_requests', '0002_mechanicrequestoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicEarning',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percent snapshot, e.g. 20.00 for 20%.', max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='GEL', max_length=3)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='accounts.mechanicprofile')),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='earning', to='service_requests.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mechanic', '-created_at'], name='service_req_mechani_2b2360_idx')],
            },
        ),
    ]
