# Generated by Django 5.2.17 on 2026-09-13 00:36

import django.core.validators
from decimal import Decimal

from django.db import migrations, models
from django.db.models import F


def copy_catalog_prices_to_final(apps, schema_editor):
    """
    Existing catalog-priced rows get an approved final price equal to the estimate.

    Null-priced Auto Key (and any other unknown estimate) stays unset.
    Amounts of 0 are not copied — unknown prices must remain null.
    """
    ServiceRequest = apps.get_model("service_requests", "ServiceRequest")
    ServiceRequest.objects.filter(
        estimated_price_amount__isnull=False,
        estimated_price_amount__gte=Decimal("0.01"),
        final_price_amount__isnull=True,
    ).update(
        final_price_amount=F("estimated_price_amount"),
        quote_status="APPROVED",
        price_confirmed_by_customer=True,
        price_confirmed_at=F("created_at"),
        price_is_estimate=False,
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("service_requests", "0003_mechanicearning"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="final_price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Authoritative agreed price. Null until set/approved.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="price_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="price_confirmed_by_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="price_proposed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="quote_status",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("PENDING", "Awaiting customer approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NONE",
                max_length=16,
            ),
        ),
        migrations.RunPython(copy_catalog_prices_to_final, noop_reverse),
    ]
