# Generated by Django 5.2.17 on 2026-09-13 00:58

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latest known mechanic position. Not a location history log.', max_digits=9, null=True, validators=[apps.common.validators.validate_latitude]),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[apps.common.validators.validate_longitude]),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
